export const ARTIFACTS = [
  {
    id: 1,
    key: 'artifact_journal',
    title: 'Weathered Journal',
    short: 'An old journal filled with faded notes.',
    full: 'This journal once belonged to someone who explored the island before you. Its pages are worn and softened by time, with only faint traces of writing left. Some parts are no longer readable, but the feeling of presence remains. It reflects quiet moments of observation and thought. A personal record of a journey that was never fully told.',
    usedFor: 'Recording notes, observations, and daily experiences.',
  },
  {
    id: 2,
    key: 'artifact_compass',
    title: 'Broken Compass',
    short: 'A compass that no longer shows direction.',
    full: 'The compass appears damaged, its needle unable to settle in one place. It slowly shifts without giving a clear direction. Whether broken or affected by something in the environment, it cannot be relied on. Still, it represents the need for guidance during uncertain journeys. Not all paths were clearly defined.',
    usedFor: 'Navigation and finding direction at sea or on land.',
  },
  {
    id: 3,
    key: 'artifact_ship_fragment',
    title: 'Ship Fragment',
    short: 'A piece of wood from an old ship.',
    full: 'This fragment was once part of a larger vessel. Its surface shows marks of long exposure to salt water and wind. Faint carvings suggest it belonged to a structured build, not just debris. Over time, it separated from its origin and ended up on the island. It carries the memory of movement and travel.',
    usedFor: 'Part of ship construction — structure or deck.',
  },
  {
    id: 4,
    key: 'artifact_bottle_note',
    title: 'Sealed Bottle Note',
    short: 'A bottle containing a preserved message.',
    full: 'Inside the bottle is a tightly rolled piece of paper, protected from the elements. The glass is slightly worn but still intact. Messages like this were often sent without certainty of being found. It suggests urgency or hope from the person who wrote it. A small attempt to leave a trace.',
    usedFor: 'Sending messages across the sea.',
  },
  {
    id: 5,
    key: 'artifact_key',
    title: 'Rusted Key',
    short: 'An old key with no known lock.',
    full: 'This key is heavy and covered with rust, shaped for a lock that no longer exists. Its purpose is unclear now, but it once secured something important. Over time, both the lock and its meaning were lost. It remains as a symbol of access to something that is no longer reachable. A simple object with an unknown story.',
    usedFor: 'Opening locked chests, doors, or containers.',
  },
  {
    id: 6,
    key: 'artifact_knot',
    title: 'Sailor\'s Knot',
    short: 'A tightly tied rope knot, preserved from years of use.',
    full: 'This rope knot has held its shape despite years of tension, salt, and wind. The fibers are worn but still strong, showing how often it was used. Knots like this were essential on ships, securing sails, cargo, and equipment. Each loop and pull was tied with purpose, often quickly and without hesitation. It reflects skill, routine, and the quiet discipline of life at sea.',
    usedFor: 'Securing sails, fastening cargo, and holding ship elements in place.',
  },
  {
    id: 7,
    key: 'artifact_coin',
    title: 'Worn Coin',
    short: 'A coin with almost no visible details.',
    full: 'The surface of the coin has been worn smooth, its original markings barely visible. It is no longer valuable in a practical sense. However, it once passed between people as part of everyday exchange. Now it remains as a small piece of forgotten transactions. A quiet trace of human activity.',
    usedFor: 'Trade and simple transactions.',
  },
  {
    id: 8,
    key: 'artifact_sail_cloth',
    title: 'Torn Sail Cloth',
    short: 'A fragment of sail fabric.',
    full: 'This piece of cloth was once part of a ship\'s sail, stretched by wind and tension. The edges are torn and uneven, showing signs of heavy use. It no longer serves its original purpose, but its structure remains recognizable. It reflects movement, travel, and reliance on natural forces. A fragment of direction and motion.',
    usedFor: 'Catching wind to move the ship.',
  },
  {
    id: 9,
    key: 'artifact_map_fragment',
    title: 'Map Fragment',
    short: 'A torn piece of an unfinished map.',
    full: 'Only part of the map remains, showing incomplete lines and shapes. It suggests routes or locations, but nothing is fully clear. The missing parts leave more questions than answers. It reflects how knowledge is often discovered in fragments. Not everything was meant to be fully understood.',
    usedFor: 'Navigation and marking locations.',
  },
  {
    id: 10,
    key: 'artifact_lantern',
    title: 'Old Lantern',
    short: 'A lantern that once provided light.',
    full: 'This lantern no longer contains a flame, but its structure is still intact. It was used during dark nights to provide visibility and guidance. Its design is simple and practical, built for function rather than decoration. Even without light, it represents direction and awareness. A tool for moving forward in darkness.',
    usedFor: 'Providing light in dark environments.',
  },
];
