export const FACTS = [
  'Pirates didn\'t always bury treasure. Most of the time, they spent it quickly or traded it at ports.',
  'Life on a pirate ship was highly structured. Everyone had a role, and breaking rules had consequences.',
  'Many pirates preferred quiet islands like this one. They were perfect for rest, repair, and staying unnoticed.',
  'Fresh water was more valuable than gold. Finding a reliable source often decided where pirates stayed.',
  'Not all pirates were criminals in the usual sense. Some were former sailors who chose freedom over strict command.',
  'Ships needed constant repair. Islands were used to fix sails, wood, and ropes.',
  'Pirates often shared everything they found. Loot was divided based on clear agreements.',
  'Maps were rarely accurate. Much of navigation relied on memory and experience.',
  'Small objects were carried everywhere. Tools, coins, and personal items rarely left their owners.',
  'Storms shaped pirate routes more than plans did. Nature often decided where they ended up.',
  'Fire was always controlled carefully. On ships and islands, it was both useful and dangerous.',
  'Pirates trusted routines. Simple daily actions helped maintain order in chaos.',
  'Many items were reused again and again. Nothing was wasted if it still had a purpose.',
  'Silence was often safer than action. Waiting and watching was part of survival.',
  'Islands like this held temporary lives. People came, stayed for a while, and moved on.',
  'Knots were a critical skill. A poorly tied rope could cost a sail or a life.',
  'Light sources were limited. Lanterns were used carefully to preserve fuel.',
  'Most pirates knew basic navigation. Even without maps, they could read the sea and sky.',
  'Supplies were always uncertain. Planning never guaranteed survival.',
  'Pirates adapted quickly. Every new place required different decisions.',
  'Some pirates left marks behind. Not as secrets, but as simple signs of presence.',
  'Weather determined daily life. Work, rest, and movement depended on conditions.',
  'Clothing was practical, not decorative. Everything worn had a function.',
  'Trust was built slowly. On islands, it mattered more than strength.',
  'Many objects had multiple uses. One tool often solved several problems.',
  'Time felt different on the island. There was no schedule, only daylight and night.',
  'Pirates rarely stayed too long in one place. Movement was part of staying safe.',
  'Even simple meals required effort. Fishing, fire, and preparation took time.',
  'The sea was both a path and a threat. It gave freedom but demanded respect.',
  'Every island held traces of past lives. Not everything was visible, but something was always left behind.',
];
