export const CATEGORIES = ['All', 'Pirate Life', 'Legends', 'Sea & Ships', 'Island Life'];

const IMG = {
  'Pirate Life': 'story_card_1',
  'Legends': 'story_card_2',
  'Sea & Ships': 'story_card_3',
  'Island Life': 'story_card_4',
};

export const STORIES = [
  {
    id: 1,
    category: 'Pirate Life',
    cardImage: IMG['Pirate Life'],
    title: 'Life at Sea',
    body: 'Life at sea was far from the romantic image often imagined today. For pirates, the ocean was both a source of freedom and a constant threat. Days were long, repetitive, and physically demanding. The crew had to maintain the ship, repair sails, clean the deck, and stay alert at all times. Salt air, humidity, and constant movement made even simple tasks exhausting.\n\nSleep was irregular and often uncomfortable. Pirates rarely had private space — most slept in shared areas, surrounded by noise, movement, and the smell of the sea. Storms could interrupt rest at any moment, forcing everyone on deck regardless of time.\n\nDespite the hardship, life at sea created a strong bond between crew members. They relied on each other for survival. Trust was essential. A single mistake could cost lives. Over time, this environment shaped a unique culture — one based on resilience, adaptability, and shared experience.',
  },
  {
    id: 2,
    category: 'Pirate Life',
    cardImage: IMG['Pirate Life'],
    title: 'Daily Routine',
    body: 'A pirate\'s day was structured around necessity rather than comfort. At sunrise, crew members were already working. Tasks were divided based on skills and roles. Some handled navigation, others maintained equipment, while others prepared food or stood watch.\n\nThere was little room for idleness. Even during calm days, the crew stayed busy. They cleaned weapons, checked supplies, and repaired anything that could fail later. The ocean did not forgive neglect.\n\nMeals were simple and repetitive. Food had to last for long journeys, so freshness was rare. Water was rationed carefully. Every resource was controlled and monitored.\n\nAt night, shifts continued. Someone was always awake, watching the horizon. The routine created discipline, even among those who lived outside traditional rules. Survival depended on consistency.',
  },
  {
    id: 3,
    category: 'Pirate Life',
    cardImage: IMG['Pirate Life'],
    title: 'Food & Survival',
    body: 'Food at sea was not about taste — it was about survival. Pirates relied on preserved goods such as dried meat, hard biscuits, and salted fish. These supplies could last for weeks, but often lost quality over time.\n\nFresh food was rare and usually obtained during stops on islands. Fruits, vegetables, and clean water were highly valued. Without them, health quickly declined. Scurvy and dehydration were real dangers.\n\nCooking conditions were limited. Fire was risky on wooden ships, so meals were simple. Many pirates ate cold or minimally prepared food.\n\nSurvival depended on planning. Running out of food or water meant serious consequences. Every decision about supplies could determine whether a journey continued or ended.',
  },
  {
    id: 4,
    category: 'Pirate Life',
    cardImage: IMG['Pirate Life'],
    title: 'Crew & Brotherhood',
    body: 'Pirate crews were built on a different kind of structure than traditional ships. While there was a captain, many decisions were shared. Crew members often had a voice, especially when it came to important matters.\n\nThis created a strong sense of equality. Everyone contributed, and everyone depended on each other. Loyalty was not just expected — it was necessary.\n\nConflicts still existed, but they were usually handled within the group. Trust was the foundation of survival. A divided crew was a vulnerable crew.\n\nOver time, these bonds became deeper than simple cooperation. Many pirates saw their crew as family. In a world full of uncertainty, this connection was one of the few stable elements they had.',
  },
  {
    id: 5,
    category: 'Pirate Life',
    cardImage: IMG['Pirate Life'],
    title: 'Rules of the Ship',
    body: 'Despite their reputation, pirates followed strict rules on board. These rules were designed to maintain order and ensure survival.\n\nCommon rules included fair distribution of resources, assigned duties, and consequences for breaking agreements. Some ships had written codes that every crew member agreed to follow.\n\nDiscipline was important. Without it, chaos could quickly take over. The ocean required coordination and structure.\n\nThese rules created a balance between freedom and responsibility. Pirates lived outside traditional systems, but they still needed organization to survive in such a harsh environment.',
  },
  {
    id: 6,
    category: 'Legends',
    cardImage: IMG['Legends'],
    title: 'The Ghost Ship',
    body: 'Among sailors and pirates alike, stories of ghost ships were some of the most feared and whispered legends. These ships were said to appear suddenly, often emerging from thick fog or during silent, windless nights. They moved without sound, their sails full yet untouched by any visible wind.\n\nThose who claimed to see them described empty decks, broken masts, or figures standing motionless, as if frozen in time. Some believed these ships were cursed — trapped between life and death, endlessly drifting across the ocean.\n\nFor pirates, encountering such a ship was considered a bad omen. Many would change course immediately, avoiding even the possibility of crossing its path. Whether real or imagined, the legend of the ghost ship reminded them that the sea held mysteries beyond human understanding.',
  },
  {
    id: 7,
    category: 'Legends',
    cardImage: IMG['Legends'],
    title: 'Cursed Treasure',
    body: 'Not all treasure was meant to be taken. Among pirate tales, cursed treasure was one of the most unsettling ideas. These were riches believed to carry consequences — objects that brought misfortune, illness, or even death to those who claimed them.\n\nStories told of crews who found hidden chests, only to face strange events afterward. Sudden storms, internal conflicts, or unexplained accidents would follow. Some said the treasure belonged to someone who had died protecting it, leaving behind a lingering presence.\n\nBecause of this, experienced pirates often approached unknown finds with caution. They understood that not every discovery was worth the risk. In a world already filled with danger, the idea of something unseen and uncontrollable was enough to make even the boldest hesitate.',
  },
  {
    id: 8,
    category: 'Legends',
    cardImage: IMG['Legends'],
    title: 'The Silent Island',
    body: 'There were islands that appeared on no map, spoken of only in fragments of stories passed between sailors. One of these was known as the Silent Island — a place where no sound seemed to exist.\n\nThose who claimed to land there described an unnatural stillness. No wind, no animals, no movement. Even footsteps felt muted, as if absorbed by the ground itself. The ocean around it remained calm, almost too calm, creating an eerie contrast to the unpredictable nature of the sea.\n\nPirates avoided such places. Silence, in their world, was not peace — it was a warning. The absence of life suggested something deeper, something hidden beneath the surface. The Silent Island became a symbol of the unknown, a place that invited curiosity but demanded distance.',
  },
  {
    id: 9,
    category: 'Legends',
    cardImage: IMG['Legends'],
    title: 'Vanished Crew',
    body: 'There were stories of ships found drifting with no crew on board. No signs of struggle, no damage — just emptiness. Supplies untouched, sails intact, and yet, not a single person remained.\n\nPirates who discovered such ships often searched for clues but found none. It was as if the crew had simply disappeared. Some believed they had abandoned the ship, though there was rarely evidence of escape. Others thought something far more mysterious had taken place.\n\nThese stories spread quickly among sailors, feeding into the belief that the ocean could claim people without explanation. The idea that an entire crew could vanish without a trace added to the growing list of things that could not be understood — only respected and feared.',
  },
  {
    id: 10,
    category: 'Legends',
    cardImage: IMG['Legends'],
    title: 'The Last Signal',
    body: 'In the darkest nights at sea, some pirates reported seeing distant lights — brief, flickering signals far beyond the horizon. These lights would appear suddenly and disappear just as quickly, leaving no trace.\n\nSome believed these were signals from lost ships, attempts to communicate across impossible distances. Others thought they were illusions, reflections of something unseen. There were even those who believed the lights came from places that no longer existed.\n\nRegardless of the explanation, these signals became part of pirate lore. They represented the thin line between reality and imagination, reminding sailors that the ocean was not just a physical space, but a place filled with unanswered questions.',
  },
  {
    id: 11,
    category: 'Sea & Ships',
    cardImage: IMG['Sea & Ships'],
    title: 'Building a Pirate Ship',
    body: 'A pirate ship was more than just a vessel — it was a lifeline. Every part of it had to be strong, reliable, and functional. Ships were often taken rather than built, but modifications were always made to suit the crew\'s needs.\n\nSpeed and maneuverability were essential. Pirates preferred ships that could quickly change direction and escape danger. Sails, ropes, and the hull were constantly checked and repaired.\n\nLiving on a ship meant understanding it completely. Every sound, every movement mattered. The crew learned to read the ship as if it were alive, responding to changes in weather and water.',
  },
  {
    id: 12,
    category: 'Sea & Ships',
    cardImage: IMG['Sea & Ships'],
    title: 'Navigation & Maps',
    body: 'Navigation was one of the most important skills at sea. Pirates relied on maps, compasses, and the stars to find their way. However, maps were often incomplete or outdated, forcing sailors to make decisions based on experience.\n\nReading the ocean was just as important as reading a map. Changes in water color, wave patterns, and wind direction all provided information. Skilled navigators could sense shifts before they became visible.\n\nMistakes in navigation could lead to being lost for days or even weeks. For pirates, this meant wasted resources and increased risk. Every journey depended on the ability to stay on course, even when the path was uncertain.',
  },
  {
    id: 13,
    category: 'Sea & Ships',
    cardImage: IMG['Sea & Ships'],
    title: 'Life on Long Voyages',
    body: 'Long voyages tested both physical and mental endurance. Days blended together, marked only by the rising and setting of the sun. Routine became the only structure in an otherwise unpredictable environment.\n\nSpace was limited, and privacy did not exist. The same faces, the same conversations, the same surroundings — all repeated endlessly. Over time, this created tension, but also a strange sense of familiarity.\n\nThe ocean could be calm for days, creating a deceptive sense of safety. Then suddenly, everything could change. Long voyages were not just about distance — they were about endurance, patience, and the ability to adapt.',
  },
  {
    id: 14,
    category: 'Sea & Ships',
    cardImage: IMG['Sea & Ships'],
    title: 'Storms and Survival',
    body: 'Storms were among the greatest threats pirates faced. Without warning, calm seas could turn violent. Waves grew higher, winds stronger, and visibility nearly disappeared.\n\nDuring a storm, every crew member had a role. Sails needed to be controlled, water removed from the deck, and the ship stabilized. Panic could be as dangerous as the storm itself.\n\nSurvival depended on coordination and experience. Those who had faced storms before knew how quickly things could escalate. After the storm passed, the damage remained — broken equipment, lost supplies, and the reminder of how fragile life at sea truly was.',
  },
  {
    id: 15,
    category: 'Sea & Ships',
    cardImage: IMG['Sea & Ships'],
    title: 'The Captain\'s Role',
    body: 'The captain was not just a leader, but a decision-maker under constant pressure. Every choice affected the crew\'s safety and survival.\n\nA good captain balanced authority with trust. While they held the final say, they often listened to the crew. Respect was earned through experience, not just position.\n\nLeadership at sea required calm thinking, especially in dangerous situations. The captain had to remain steady, even when everything else was uncertain. Their role was not about control, but about guiding the crew through the unknown.',
  },
  {
    id: 16,
    category: 'Island Life',
    cardImage: IMG['Island Life'],
    title: 'Living Beyond the Ship',
    body: 'When pirates arrived on an island, everything changed. Life was no longer confined to the narrow deck of a ship. There was space to move, to breathe, and to rest.\n\nThey would explore the area first, checking for water sources, safe ground, and signs of danger. Choosing the right place to stay was important. Too close to the shore meant visibility, too deep inland meant difficulty returning to the ship.\n\nOn land, routines shifted. Instead of constant movement, there was time to pause. Some repaired equipment, others collected resources, and some simply sat in silence, adjusting to the stillness.\n\nThese moments on the island were rare but valuable. They allowed pirates to reset, physically and mentally, before returning to the unpredictable life at sea.',
  },
  {
    id: 17,
    category: 'Island Life',
    cardImage: IMG['Island Life'],
    title: 'Finding Fresh Water',
    body: 'Fresh water was one of the most important resources pirates searched for on any island. Without it, survival was limited to only a few days.\n\nThey learned to recognize signs of water — certain plants, changes in terrain, or the sound of distant streams. Sometimes it required digging, other times careful exploration through dense areas.\n\nWater was never wasted. Every drop mattered. It was stored, rationed, and protected. Even a small source could determine how long the crew could stay.\n\nThe search for water was not just practical — it was a reminder of how dependent they were on the environment around them.',
  },
  {
    id: 18,
    category: 'Island Life',
    cardImage: IMG['Island Life'],
    title: 'Food and Survival',
    body: 'Food on the island was unpredictable. Pirates could not rely on the same resources every time. They had to adapt.\n\nFishing was often the safest option, but it required time and patience. On land, they searched for fruits, roots, or anything edible. Experience played a key role — knowing what was safe and what was not.\n\nCooking was simple. Fire, basic tools, and whatever was available. Meals were not about comfort, but survival.\n\nDespite the simplicity, these moments were important. Eating together created a sense of stability, even in uncertain conditions.',
  },
  {
    id: 19,
    category: 'Island Life',
    cardImage: IMG['Island Life'],
    title: 'Temporary Shelter',
    body: 'Building shelter was a quick but necessary task. Pirates rarely stayed in one place for long, so structures were simple and functional.\n\nThey used what was available — wood, leaves, fabric from the ship. The goal was protection, not comfort. Shelter needed to withstand wind, rain, and unexpected changes in weather.\n\nPlacement mattered. Too exposed, and it would not last. Too hidden, and it could be difficult to access.\n\nThese temporary structures often disappeared over time, leaving behind only traces. But for a short period, they became a place of rest and recovery.',
  },
  {
    id: 20,
    category: 'Island Life',
    cardImage: IMG['Island Life'],
    title: 'Moments of Rest',
    body: 'Life at sea was constant movement. The island offered something different — stillness.\n\nThere were moments when nothing needed to be done. No waves to fight, no sails to adjust. Just quiet surroundings and time to think.\n\nSome pirates used this time to reflect, others simply rested. Even short pauses could make a difference.\n\nThese moments were not about luxury. They were about balance. In a life filled with uncertainty, even a brief sense of calm was valuable.',
  },
];
